#144 specific on_change
Avaiga/taipy-gui pull request #145
Opened 2022-03-24 12:32 UTC by FredLL-Avaiga

2022-03-24 14:59 UTC, FabienLelaquais requested changes
I havent't seen the 'date' control factory update...
Nor did I see the 'slider' documentation update.

Shouldn't 'expandable' be an on_action component?

2022-03-24 14:59 UTC, FabienLelaquais commented on gui/doc/on_change.csv
> +<li>gui instance</li>
gui?

2022-03-24 14:59 UTC, FabienLelaquais commented on gui/doc/on_change.csv
> +﻿Name,Type,Default,Doc
I guess we'll have to fill this in...

2022-03-24 14:59 UTC, FabienLelaquais commented on taipy/gui/gui.py
> +                warnings.warn(f"{on_change or 'on_change'}: function invocation exception: {e}")
Hmmm.
May be "'on_change' callback function raised an exception: {e}"?

2022-03-24 15:10 UTC, FredLL-Avaiga commented on gui/doc/on_change.csv
> +<li>gui instance</li>
fixed

2022-03-24 15:10 UTC, FredLL-Avaiga commented on gui/doc/on_change.csv
> +﻿Name,Type,Default,Doc
What do you mean ?

2022-03-24 15:13 UTC, FredLL-Avaiga commented
> I havent't seen the 'date' control factory update... 

It's in there

> Nor did I see the 'slider' documentation update.

Fixed
 
> Shouldn't 'expandable' be an on_action component?

why ?

2022-03-24 15:39 UTC, FabienLelaquais approved these changes
Excellentissimo

2022-03-24 15:39 UTC, FabienLelaquais commented on gui/doc/on_change.csv
> +﻿Name,Type,Default,Doc
I mean we need doc on the parameters. No big deal.

2022-03-25 06:23 UTC, FabienLelaquais approved these changes
Looks perfect to me!

2022-03-25 09:16 UTC, dinhlongviolin1 approved these changes
Great job

2022-03-25 09:53 UTC, merged