simplify dialog (#166)
Avaiga/taipy-gui pull request #169
Opened 2022-03-31 15:09 UTC by FredLL-Avaiga

after discussion with Florian

2022-03-31 15:35 UTC, FabienLelaquais requested changes
I am very surprised not to see 'dialog.md' modified here...

2022-03-31 15:35 UTC, FabienLelaquais commented on gui/doc/dialog.csv
> +<li>args: List with first element containing the index of the label selected.</li>
=> "List where the first element contains the index of the selected label"

2022-03-31 15:35 UTC, FabienLelaquais commented on gui/doc/dialog.csv
> +labels, str|list[str],None,"A list of labels to show as buttons at the bottom of the dialog. The index of the button in the list is reported as args in the _on_action_ function (-1 for the close icon
to show in a row of buttons

2022-03-31 15:35 UTC, FabienLelaquais commented on gui/src/components/Taipy/Dialog.tsx
> +                console.info(`Error while parsing dialog.labels\n${(e as Error).message || e}`);
'while' is useless, I guess...

2022-03-31 15:35 UTC, FabienLelaquais commented on gui/src/components/Taipy/Dialog.tsx
> +                <DialogActions>
Too easy, React, hu?

2022-03-31 15:52 UTC, FredLL-Avaiga commented
> I am very surprised not to see 'dialog.md' modified here...

Un oubli !

2022-03-31 19:45 UTC, dinhlongviolin1 approved these changes
Great job

2022-04-01 05:19 UTC, FabienLelaquais approved these changes
Great!

2022-04-01 07:31 UTC, merged