Protect data & co.
Avaiga/taipy-gui pull request #32
Opened 2022-02-15 15:16 UTC by FredLL-Avaiga

- #16 protect data (State)
- #15 encapsulation (fix parameter.date support)
- #14 early variable binding
- #10 easy charts and tables ```<{[26,74,65]}|chart|type=pie|>```
- #18 date_selector -> date
- #4 vertical indicator ```<|MAE: {mae}|indicator|value={val}|min=20|max=-20|orientation=vertical|>```

2022-02-15 15:40 UTC, FabienLelaquais requested changes
Excellent, excellent job.
A few remarks that might need tiny changes...

2022-02-15 15:40 UTC, FabienLelaquais commented on gui/src/components/Taipy/DateSelector.tsx
> +                        className={getSuffixedClassNames(className, "-picker")}
The code is used three times. Better to factorize?
And... not too sure about the 'picker' part...

2022-02-15 15:40 UTC, FabienLelaquais commented on gui/src/components/Taipy/DateSelector.tsx
> +                    id={id + "-field"}
Why not use 'id' at this point? The input field is not rendered...

2022-02-15 15:40 UTC, FabienLelaquais commented on tests/taipy/gui/control/test_date_selector.py
> +def test_date_md_1(gui: Gui, helpers):
You may even want to rename the file itself at this point...

2022-02-15 15:40 UTC, FabienLelaquais commented on taipy/gui/utils/_state.py
> +import typing as t
That really looks great. Eager to see that in action!
Should the Gui object know about those variables though?

2022-02-15 15:40 UTC, FabienLelaquais commented on taipy/gui/data/array_dict_data_accessor.py
> +            if isinstance(value[0], (str, int, float, bool)):
Shouldn't we test is all values are kind of the same type?
Or maybe the DataFrame constructor does it?

2022-02-15 15:44 UTC, FredLL-Avaiga commented on gui/src/components/Taipy/DateSelector.tsx
> +                        className={getSuffixedClassNames(className, "-picker")}
Wrong copy/paste, it should only be used 2 times with the same suffix

2022-02-15 15:44 UTC, FredLL-Avaiga commented on gui/src/components/Taipy/DateSelector.tsx
> +                        className={getSuffixedClassNames(className, "-picker")}
And in different cases

2022-02-15 15:45 UTC, FredLL-Avaiga commented on gui/src/components/Taipy/DateSelector.tsx
> +                    id={id + "-field"}
Id is used at the parent level

2022-02-15 15:46 UTC, FredLL-Avaiga commented on tests/taipy/gui/control/test_date_selector.py
> +def test_date_md_1(gui: Gui, helpers):
Will do

2022-02-15 15:46 UTC, FredLL-Avaiga commented on taipy/gui/utils/_state.py
> +import typing as t
?
It does

2022-02-15 15:47 UTC, FredLL-Avaiga commented on taipy/gui/data/array_dict_data_accessor.py
> +            if isinstance(value[0], (str, int, float, bool)):
I guess dataframe will throw an error if it's not happy 😁

2022-02-15 15:48 UTC, FredLL-Avaiga commented on gui/src/components/Taipy/DateSelector.tsx
> +                        className={getSuffixedClassNames(className, "-picker")}
Do you have another proposal for picker?

2022-02-16 04:08 UTC, dinhlongviolin1 approved these changes
Great job! I just have 1 question. Since gui has been replaced by state, from what I understand, the users wont be able to access gui public method through state. Correct me if I am wrong

2022-02-16 04:08 UTC, dinhlongviolin1 commented on tests/taipy/gui/data/test_arry_dict_data_accessor.py
> +import pytest
File name typo

2022-02-16 04:08 UTC, dinhlongviolin1 commented on taipy/gui/gui.py
> +        if hasattr(self, "on_change") and isinstance(self.on_change, FunctionType):
Thanks

2022-02-16 04:08 UTC, dinhlongviolin1 commented on taipy/gui/gui.py
> +        if hasattr(self, "on_action") and isinstance(self.on_action, FunctionType):
Thanks again

2022-02-16 08:12 UTC, FredLL-Avaiga commented on tests/taipy/gui/data/test_arry_dict_data_accessor.py
> +import pytest
Fixed

2022-02-16 08:13 UTC, FredLL-Avaiga commented
> Great job! I just have 1 question. Since gui has been replaced by state, from what I understand, the users wont be able to access gui public method through state. Correct me if I am wrong
That's true and it's "by design":
- the user variable are accessed via State
- the Gui behavior via Gui

2022-02-16 08:24 UTC, dinhlongviolin1 commented
> > Great job! I just have 1 question. Since gui has been replaced by state, from what I understand, the users wont be able to access gui public method through state. Correct me if I am wrong
> > That's true and it's "by design":
> 
> * the user variable are accessed via State
> * the Gui behavior via Gui

From what I have seen in the code, users can't access gui directly from the parameters anymore right

2022-02-16 08:26 UTC, FredLL-Avaiga commented
> From what I have seen in the code, users can't access gui directly from the parameters anymore right

they should have an gui instance globally accessible ;-)

2022-02-16 08:36 UTC, dinhlongviolin1 commented
> > From what I have seen in the code, users can't access gui directly from the parameters anymore right
> 
> they should have an gui instance globally accessible ;-)

That is exactly what I am expecting. If Fabien's ok with it, I am

2022-02-16 10:46 UTC, FabienLelaquais approved these changes
👍

2022-02-16 10:47 UTC, merged