fix notebook bug (#362)
Avaiga/taipy-gui pull request #377
Opened 2022-08-26 04:42 UTC by dinhlongviolin1

Fix Bug #362 
The problem is much simpler than I thought, the ipykernel used by vscode have the same --force-https argument that we have

2022-08-26 07:15 UTC, FredLL-Avaiga requested changes

2022-08-26 07:15 UTC, FredLL-Avaiga commented on src/taipy/gui/config.py
>              config["force_https"] = True
Should we change the config param from force_https to use_https everywhere for the sake of uniformity and doc ?

2022-08-30 07:19 UTC, FredLL-Avaiga approved these changes
I guess that https will be provided via a proxy ?

2022-08-30 07:46 UTC, dinhlongviolin1 commented
> I guess that https will be provided via a proxy ?

Definitely

2022-08-30 08:19 UTC, FabienLelaquais approved these changes
Less is more.

2022-08-30 09:45 UTC, merged