Manage user Data
Avaiga/taipy-gui pull request #38
Opened 2022-02-16 17:01 UTC by FredLL-Avaiga

- #35 extract all user data from Gui and into _UserData
- #37 add a render property to chart
- #6 assign dictionnary

2022-02-16 17:37 UTC, FabienLelaquais requested changes
Minor comment but including renaming, potentially.
You have to talk to me abot *drill.
Looks really nice though

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/utils/_user_data.py
> +class _UserData:
_UserData is far too vague for me.
What do you think about `_Bindings`?

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/utils/__init__.py
> +from .attributes import delscopeattr, getscopeattr, getscopeattr_drill, getuserattr, hasscopeattr, hasuserattr, setscopeattr, setscopeattr_drill
Do we really need those?

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/utils/_state.py
> +    def __init__(self, gui: "Gui") -> None:
No type for 'gui', and what about this default value?!

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/utils/attributes.py
> +from operator import attrgetter
I suspect this file would be '_attributes.py'?

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/utils/attributes.py
> +        return getattr(gui._get_user_data()._get_data_scope(), name, more[0])
Why 'more[0]' and not 'more'? I guess that would be more useful...

2022-02-16 17:37 UTC, FabienLelaquais commented on tests/taipy/gui/gui_specific/test_mapdict.py
> +    assert isinstance(gui._Gui__state.d, _MapDictionary)
No checks on the values?

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/gui.py
> +    def _get_user_data(self):
... and that would be '_bindings()'... (see other remark on naming)

2022-02-16 17:37 UTC, FabienLelaquais commented on taipy/gui/gui.py
>      def bind_var(self, var_name: str) -> bool:
I think we could group `bind_func()` and `bind_var()` in the same `bind()` function.
I wonder if `bind_var_val()` is of any use...

2022-02-16 18:32 UTC, FredLL-Avaiga commented on taipy/gui/gui.py
>      def bind_var(self, var_name: str) -> bool:
in theory bind_func doesn't need the scope ...

2022-02-16 18:32 UTC, FredLL-Avaiga commented on taipy/gui/gui.py
> +    def _get_user_data(self):
OK

2022-02-16 18:33 UTC, FredLL-Avaiga commented on tests/taipy/gui/gui_specific/test_mapdict.py
> +    assert isinstance(gui._Gui__state.d, _MapDictionary)
I could ...

2022-02-16 18:35 UTC, FredLL-Avaiga commented on taipy/gui/utils/attributes.py
> +        return getattr(gui._get_user_data()._get_data_scope(), name, more[0])
I think more is a list (or Iterable) ...

2022-02-16 18:35 UTC, FredLL-Avaiga commented on taipy/gui/utils/attributes.py
> +from operator import attrgetter
ok

2022-02-16 18:36 UTC, FredLL-Avaiga commented on taipy/gui/utils/_state.py
> +    def __init__(self, gui: "Gui") -> None:
?

2022-02-16 18:36 UTC, FredLL-Avaiga commented on taipy/gui/utils/__init__.py
> +from .attributes import delscopeattr, getscopeattr, getscopeattr_drill, getuserattr, hasscopeattr, hasuserattr, setscopeattr, setscopeattr_drill
we do

2022-02-16 18:36 UTC, FredLL-Avaiga commented on taipy/gui/utils/_user_data.py
> +class _UserData:
Agreed

2022-02-17 02:21 UTC, dinhlongviolin1 approved these changes
A good improvement to the structure. I must admit I don't like the variable binding to Gui itself.  Binding user variable to user data is a much better way of encapsulating data binding. Great job Fred!

2022-02-17 02:21 UTC, dinhlongviolin1 commented on taipy/gui/utils/attributes.py
> +def getuserattr(gui: "Gui", name: str, *more) -> t.Any:
I have never seen this, is it ok for Gui to be in double quotes

2022-02-17 02:21 UTC, dinhlongviolin1 commented on taipy/gui/utils/attributes.py
> +from operator import attrgetter
Nice utils file

2022-02-17 06:45 UTC, FredLL-Avaiga commented on taipy/gui/utils/_state.py
> +    def __init__(self, gui: "Gui") -> None:
it's a way to work around circular dependencies

2022-02-17 06:53 UTC, FredLL-Avaiga commented on taipy/gui/utils/attributes.py
> +def getuserattr(gui: "Gui", name: str, *more) -> t.Any:
for circular dependencies ...

2022-02-17 07:01 UTC, FredLL-Avaiga commented on taipy/gui/gui.py
>      def bind_var(self, var_name: str) -> bool:
bind_var_val : 115 occurrences in 25 files
OK mainly in tests
but outside of tests: 7 occurrences in 3 files

2022-02-17 08:11 UTC, FabienLelaquais approved these changes
Go for it!

2022-02-17 08:12 UTC, merged