#572 theme & css toolkit
Avaiga/taipy-gui pull request #620
Opened 2023-02-22 17:21 UTC by FredLL-Avaiga

toolkit is commanded by the toolkit bool run parameter
configurable through optional toolkit_config run parameter
`Gui(page=page).run(toolkit=True, toolkit_config={"color_primary": "#00FF00"})`

2023-02-24 08:25 UTC, FabienLelaquais requested changes
Excellent starting point.

A few changes that I think are relevant:

- Globally rename 'toolkit' to 'stylekit', rename 'toolkit_config' to 'stylekit_variables'.
     => git mv public/toolkit public/stylekit
- stylekit=True  should be the default, That should be the future of Taipy, with as little code as possible (no stylekit=True in every Taipy GUI app).
- homogeneity: please use the same coding style for css (space before {, endling line skip, 2 or 4 space chars for indentation, etc.)
- CSS file headers to be similar as well - including license?
-  There are very generic class names everywhere... like 'container'

2023-02-27 09:08 UTC, JaufreyTpy commented
@FredLL-Avaiga I think that's a great starting point indeed!
There is only one thing I would do differently, and it would be to move some theme styles from this `gui/src/themes/stylekit.ts` file directly to the relevant component's files, as styled component rules. This would be better for component specific styles to stay where they are useful rather than in a deported global file.
I can do that part if you like.

@FabienLelaquais as for generic class names : "container", for example, is a name commonly used in multiple big and well known frameworks: CSS frameworks like Bootstrap or JS frameworks like Material UI (to cite just them) use this class (or component) name for that very specific case of limiting content width and centering it into the window. I get why you feel it's generic, but in the CSS/JS ecosystem, container (without affix) actually is a meaningful name.

2023-02-27 09:11 UTC, JaufreyTpy approved these changes

2023-02-27 09:12 UTC, FredLL-Avaiga commented
> move some theme styles from this `gui/src/themes/stylekit.ts` file directly to the relevant component's files, as styled component rules.
Why not but this need to be activated only if window.taipyConfig.stylekit ids defined ...

2023-02-27 09:25 UTC, JaufreyTpy commented
> this need to be activated only if window.taipyConfig.stylekit ids defined ...

Yes, but there are some normalization and improvement styles here that could be implemented right away, whether stylekit is ON or not, I think. Like making buttons and input the same height, for obvious example.

2023-02-27 13:45 UTC, FredLL-Avaiga commented on gui/src/themes/stylekit.ts
> +                    ".taipy-tree &": {
@JaufreyTpy I don't understand these rules: for taipy-tree and taipy-layout, the components are not embedded in a FormControl ?
(this is valid for taipy-selector though and indeed I will apply it directly to the taipy component)

2023-02-27 13:50 UTC, FredLL-Avaiga commented on gui/src/themes/stylekit.ts
> +                    ".taipy-tree &": {
oh sorry, I think I read it wrong.

2023-02-27 13:52 UTC, FredLL-Avaiga commented on gui/src/themes/stylekit.ts
> +                    ".taipy-tree &": {
fro taipy-ree and taipy-layout these rules address the included FormControl (ie the TextField inside the taipy-tree Box)

2023-02-27 16:10 UTC, FabienLelaquais commented
The last commit looks neat to me: a straightforward way to get tests through.
Now... would it be possible before the merge to "git mv gui/public/stylekit/visual-elements/taipy-blocks" and "taipy-controls" to "blocks" and "controls" respectively? That prefix (even worse at this level) makes very little sense to me
Thx

2023-02-27 16:47 UTC, FabienLelaquais approved these changes
👌

2023-02-27 16:47 UTC, FabienLelaquais commented on src/taipy/gui/gui.py
> +            if script_file.with_suffix(".css").exists():
Finally! Thx!

2023-02-27 16:48 UTC, merged