#592 toggle as navbar
Avaiga/taipy-gui pull request #915
Opened 2023-09-14 14:41 UTC by FredLL-Avaiga

make toggle look like navbar via class toggle-navbar (in stylekit)

2023-09-14 15:04 UTC, dinhlongviolin1 approved these changes

2023-09-15 08:35 UTC, FabienLelaquais requested changes
Please

2023-09-15 08:35 UTC, FabienLelaquais commented on gui/public/stylekit/controls/toggle.css
> +.toggle-navbar .MuiButtonBase-root {
Should't we protect that rule so it applies only in the taipy-toggle CSS class context?

2023-09-15 09:20 UTC, FabienLelaquais approved these changes
👍

2023-09-15 09:28 UTC, merged